# Generated by Django 4.1.7 on 2023-03-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=60)),
                ("due_date", models.DateTimeField(null=True)),
            ],
        ),
    ]
