# Generated by Django 4.1.7 on 2023-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('todo', 'Todo')], default='todo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
