# Generated by Django 4.1.7 on 2023-03-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
