# Generated by Django 4.1.7 on 2023-03-11 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot8', '0003_alter_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
